"""Add created_at column to BestNine

Revision ID: 378c610dfcee
Revises: bd3b63eb513a
Create Date: 2026-04-09 10:46:54.473996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378c610dfcee'
down_revision = 'bd3b63eb513a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('best_nine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    with op.batch_alter_table('best_nine', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
